// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access_point.proto

package access_point

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserEnterRequest struct {
	UserGroupID          string   `protobuf:"bytes,1,opt,name=userGroupID,proto3" json:"userGroupID,omitempty"`
	AccessPointID        int32    `protobuf:"varint,2,opt,name=accessPointID,proto3" json:"accessPointID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEnterRequest) Reset()         { *m = UserEnterRequest{} }
func (m *UserEnterRequest) String() string { return proto.CompactTextString(m) }
func (*UserEnterRequest) ProtoMessage()    {}
func (*UserEnterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74d5120fed7fa438, []int{0}
}

func (m *UserEnterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEnterRequest.Unmarshal(m, b)
}
func (m *UserEnterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEnterRequest.Marshal(b, m, deterministic)
}
func (m *UserEnterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEnterRequest.Merge(m, src)
}
func (m *UserEnterRequest) XXX_Size() int {
	return xxx_messageInfo_UserEnterRequest.Size(m)
}
func (m *UserEnterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEnterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserEnterRequest proto.InternalMessageInfo

func (m *UserEnterRequest) GetUserGroupID() string {
	if m != nil {
		return m.UserGroupID
	}
	return ""
}

func (m *UserEnterRequest) GetAccessPointID() int32 {
	if m != nil {
		return m.AccessPointID
	}
	return 0
}

type UserEnterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AtCapacity           bool     `protobuf:"varint,2,opt,name=at_capacity,json=atCapacity,proto3" json:"at_capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEnterReply) Reset()         { *m = UserEnterReply{} }
func (m *UserEnterReply) String() string { return proto.CompactTextString(m) }
func (*UserEnterReply) ProtoMessage()    {}
func (*UserEnterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_74d5120fed7fa438, []int{1}
}

func (m *UserEnterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEnterReply.Unmarshal(m, b)
}
func (m *UserEnterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEnterReply.Marshal(b, m, deterministic)
}
func (m *UserEnterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEnterReply.Merge(m, src)
}
func (m *UserEnterReply) XXX_Size() int {
	return xxx_messageInfo_UserEnterReply.Size(m)
}
func (m *UserEnterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEnterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserEnterReply proto.InternalMessageInfo

func (m *UserEnterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserEnterReply) GetAtCapacity() bool {
	if m != nil {
		return m.AtCapacity
	}
	return false
}

type UserExitRequest struct {
	AccessPointID        int32    `protobuf:"varint,2,opt,name=accessPointID,proto3" json:"accessPointID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExitRequest) Reset()         { *m = UserExitRequest{} }
func (m *UserExitRequest) String() string { return proto.CompactTextString(m) }
func (*UserExitRequest) ProtoMessage()    {}
func (*UserExitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74d5120fed7fa438, []int{2}
}

func (m *UserExitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExitRequest.Unmarshal(m, b)
}
func (m *UserExitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExitRequest.Marshal(b, m, deterministic)
}
func (m *UserExitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExitRequest.Merge(m, src)
}
func (m *UserExitRequest) XXX_Size() int {
	return xxx_messageInfo_UserExitRequest.Size(m)
}
func (m *UserExitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserExitRequest proto.InternalMessageInfo

func (m *UserExitRequest) GetAccessPointID() int32 {
	if m != nil {
		return m.AccessPointID
	}
	return 0
}

type UserExitReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExitReply) Reset()         { *m = UserExitReply{} }
func (m *UserExitReply) String() string { return proto.CompactTextString(m) }
func (*UserExitReply) ProtoMessage()    {}
func (*UserExitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_74d5120fed7fa438, []int{3}
}

func (m *UserExitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExitReply.Unmarshal(m, b)
}
func (m *UserExitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExitReply.Marshal(b, m, deterministic)
}
func (m *UserExitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExitReply.Merge(m, src)
}
func (m *UserExitReply) XXX_Size() int {
	return xxx_messageInfo_UserExitReply.Size(m)
}
func (m *UserExitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExitReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserExitReply proto.InternalMessageInfo

func (m *UserExitReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserEnterRequest)(nil), "UserEnterRequest")
	proto.RegisterType((*UserEnterReply)(nil), "UserEnterReply")
	proto.RegisterType((*UserExitRequest)(nil), "UserExitRequest")
	proto.RegisterType((*UserExitReply)(nil), "UserExitReply")
}

func init() { proto.RegisterFile("access_point.proto", fileDescriptor_74d5120fed7fa438) }

var fileDescriptor_74d5120fed7fa438 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x8e, 0x2f, 0xc8, 0xcf, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a,
	0xe2, 0x12, 0x08, 0x2d, 0x4e, 0x2d, 0x72, 0xcd, 0x2b, 0x49, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d, 0x72, 0x2f, 0xca, 0x2f, 0x2d, 0xf0,
	0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x16, 0x12, 0x52, 0xe1, 0xe2, 0x85, 0x98,
	0x15, 0x00, 0x32, 0xca, 0xd3, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0x55, 0x50, 0xc9,
	0x9b, 0x8b, 0x0f, 0xc9, 0xec, 0x82, 0x9c, 0x4a, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0x52, 0xb0, 0x1a,
	0xb0, 0xa9, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x3c, 0x17, 0x77, 0x62, 0x49, 0x7c, 0x72, 0x62, 0x41,
	0x62, 0x72, 0x66, 0x49, 0x25, 0xd8, 0x3c, 0x8e, 0x20, 0xae, 0xc4, 0x12, 0x67, 0xa8, 0x88, 0x92,
	0x39, 0x17, 0x3f, 0xd8, 0xb0, 0x8a, 0xcc, 0x12, 0x98, 0x3b, 0x89, 0x73, 0x85, 0x26, 0x17, 0x2f,
	0x42, 0x23, 0x5e, 0x47, 0x18, 0x65, 0x70, 0x71, 0x3b, 0x22, 0xf4, 0x0a, 0xe9, 0x72, 0xb1, 0xa6,
	0x82, 0xdc, 0x2e, 0x24, 0xa8, 0x87, 0x1e, 0x46, 0x52, 0xfc, 0x7a, 0xa8, 0x5e, 0x53, 0x62, 0x10,
	0xd2, 0xe2, 0x62, 0x49, 0xad, 0xc8, 0x2c, 0x11, 0x12, 0xd0, 0x43, 0x73, 0xa8, 0x14, 0x9f, 0x1e,
	0x8a, 0x0b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xa1, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0x59, 0x57, 0xe0, 0x93, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessPointClient is the client API for AccessPoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessPointClient interface {
	Enter(ctx context.Context, in *UserEnterRequest, opts ...grpc.CallOption) (*UserEnterReply, error)
	Exit(ctx context.Context, in *UserExitRequest, opts ...grpc.CallOption) (*UserExitReply, error)
}

type accessPointClient struct {
	cc *grpc.ClientConn
}

func NewAccessPointClient(cc *grpc.ClientConn) AccessPointClient {
	return &accessPointClient{cc}
}

func (c *accessPointClient) Enter(ctx context.Context, in *UserEnterRequest, opts ...grpc.CallOption) (*UserEnterReply, error) {
	out := new(UserEnterReply)
	err := c.cc.Invoke(ctx, "/AccessPoint/enter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessPointClient) Exit(ctx context.Context, in *UserExitRequest, opts ...grpc.CallOption) (*UserExitReply, error) {
	out := new(UserExitReply)
	err := c.cc.Invoke(ctx, "/AccessPoint/exit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessPointServer is the server API for AccessPoint service.
type AccessPointServer interface {
	Enter(context.Context, *UserEnterRequest) (*UserEnterReply, error)
	Exit(context.Context, *UserExitRequest) (*UserExitReply, error)
}

// UnimplementedAccessPointServer can be embedded to have forward compatible implementations.
type UnimplementedAccessPointServer struct {
}

func (*UnimplementedAccessPointServer) Enter(ctx context.Context, req *UserEnterRequest) (*UserEnterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enter not implemented")
}
func (*UnimplementedAccessPointServer) Exit(ctx context.Context, req *UserExitRequest) (*UserExitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}

func RegisterAccessPointServer(s *grpc.Server, srv AccessPointServer) {
	s.RegisterService(&_AccessPoint_serviceDesc, srv)
}

func _AccessPoint_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEnterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccessPoint/Enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServer).Enter(ctx, req.(*UserEnterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessPoint_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccessPoint/Exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServer).Exit(ctx, req.(*UserExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessPoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AccessPoint",
	HandlerType: (*AccessPointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "enter",
			Handler:    _AccessPoint_Enter_Handler,
		},
		{
			MethodName: "exit",
			Handler:    _AccessPoint_Exit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access_point.proto",
}
